POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
    "username": "gang",
    "age": "22",
    "gender": "남성",
    "mbti": "esfp",
    "residence": "경기도 용인시",
    "height": "175",   
    "keyword": ["토끼상", "곰상"],
    "idealAge": [22, 23],
    "idealMbti": ["istj"],
    "idealHeight": [162, 164],
    "idealKeyword": ["마른", "근육질"],
}